### ISSUE TITLE
Deal with the security vulnerability warning on GitHub

### ISSUE THREAD

**Issue by gunnarbeutner** [Icinga/icinga-vagrant#120]
This pops up when opening the repository:

![github-vagrant-repo](https://user-images.githubusercontent.com/388571/36138491-dc5097e8-1099-11e8-8acb-e0673e8df3cf.png)

**Comment by dnsmichi** [comment]
This is pulled in by Puppet modules which manage their dependencies on their own. I don't have any influence here, nor will start patching these Puppet modules. I have dismissed that already in the past, seems this is now triggered again with the huge Puppet 4 update.
