### ISSUE TITLE
Demo with my servers?

### ISSUE THREAD

**Issue by tjohnston-cd** [Icinga/icinga-vagrant#165]
## Expected Behavior
I would like to use this demo with my servers, rather than the Icinga demo servers.
This would make for a much more convincing demo.

## Current Behavior
Currently, I have been able to achieve this by editing [in here](https://github.com/Icinga/icinga-vagrant/tree/master/.puppet/modules/profiles/templates/icinga/icinga2/config/demo) and adjusting things at runtime with Icinga Director from the web UI.

To do this, I had to tear down a bunch of the BPs and other features I don't have an immediate use for. In my case, I just want to measure a bunch of basic stats (load, uptime etc) on a handful of machines on my network, then supply the data to Influx/Es/whatever and dashboard it with Grafana.

## Possible Solution
Not sure what could be done differently. Are other people doing this? Or is it better to just install from scratch? (e.g. by following [this guide](https://monitoring-portal.org/t/icinga-installation-guide-1o1/3430))

Any thoughts would be appreciated! Thanks.

**Comment by dnsmichi** [comment]
I guess everyone is forking this repository and modifying it for their own needs. The demo configuration was made for showing what's possible with the modules and integrations, and shall only serve as inspiration. I don't want to go the route with teaching users to use Hiera/Puppet, neither should `vagrant up` be complicated with custom mounted shares for configuration files, etc.

In any attempt, you need to learn about Icinga and its components prior to modifying something. Especially how the configuration DSL works, and how everything connects.

**Comment by tjohnston-cd** [comment]
Fair enough. Thanks for the info!
