### ISSUE TITLE
/sbin/ifup: configuration for eth1 not found

### ISSUE THREAD

**Issue by SteveEdson** [Icinga/icinga-vagrant#19]
Steps to reproduce (Mac OS Sierra 10.12):

- `git clone git@github.com:Icinga/icinga-vagrant.git`
- `cd icinga-vagrant/icinga2x`
- `vagrant up` 

<details>
<pre>
<code>
vagrant up
Bringing machine 'icinga2' up with 'virtualbox' provider...
==> icinga2: Box 'centos-71-x64-vbox' could not be found. Attempting to find and install...
    icinga2: Box Provider: virtualbox
    icinga2: Box Version: >= 0
==> icinga2: Box file was not detected as metadata. Adding it directly...
==> icinga2: Adding box 'centos-71-x64-vbox' (v0) for provider: virtualbox
    icinga2: Downloading: http://boxes.icinga.com/centos-71-x64-vbox.box
==> icinga2: Successfully added box 'centos-71-x64-vbox' (v0) for 'virtualbox'!
==> icinga2: Importing base box 'centos-71-x64-vbox'...
==> icinga2: Matching MAC address for NAT networking...
==> icinga2: Setting the name of the VM: icinga2x_icinga2_1484818343423_81986
==> icinga2: Fixed port collision for 22 => 2222. Now on port 2200.
==> icinga2: Clearing any previously set network interfaces...
==> icinga2: Preparing network interfaces based on configuration...
    icinga2: Adapter 1: nat
    icinga2: Adapter 2: hostonly
==> icinga2: Forwarding ports...
    icinga2: 22 (guest) => 2082 (host) (adapter 1)
    icinga2: 80 (guest) => 8082 (host) (adapter 1)
    icinga2: 8003 (guest) => 8083 (host) (adapter 1)
    icinga2: 22 (guest) => 2200 (host) (adapter 1)
==> icinga2: Running 'pre-boot' VM customizations...
==> icinga2: Booting VM...
==> icinga2: Waiting for machine to boot. This may take a few minutes...
    icinga2: SSH address: 127.0.0.1:2200
    icinga2: SSH username: vagrant
    icinga2: SSH auth method: private key
==> icinga2: Machine booted and ready!
==> icinga2: Checking for guest additions in VM...
    icinga2: The guest additions on this VM do not match the installed version of
    icinga2: VirtualBox! In most cases this is fine, but in rare cases it can
    icinga2: prevent things such as shared folders from working properly. If you see
    icinga2: shared folder errors, please make sure the guest additions within the
    icinga2: virtual machine match the version of VirtualBox you have installed on
    icinga2: your host and reload your VM.
    icinga2:
    icinga2: Guest Additions Version: 4.3.28
    icinga2: VirtualBox Version: 5.1
==> icinga2: [vagrant-hostsupdater] Checking for host entries
==> icinga2: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> icinga2: [vagrant-hostsupdater]   192.168.33.5  icinga2  # VAGRANT: 2b782b5c1d5936c0f55d22b926edb70f (icinga2) / fcaaed22-0c70-4340-b34e-b0176b75dc01
==> icinga2: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
Password:
==> icinga2: Setting hostname...
==> icinga2: Configuring and enabling network interfaces...
==> icinga2: Mounting shared folders...
    icinga2: /vagrant => /Users/steveedson/repos/servers/icinga-vagrant/icinga2x
    icinga2: /tmp/vagrant-puppet/modules-26a5f480deed6fbeb151d8a7b1d2ab8b => /Users/steveedson/repos/servers/icinga-vagrant/modules
    icinga2: /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513 => /Users/steveedson/repos/servers/icinga-vagrant/icinga2x/manifests
==> icinga2: Running provisioner: shell...
    icinga2: Running: /var/folders/fv/zq88lb_j7zg2v0vhcnh31lpxvgyx12/T/vagrant-shell20170119-25794-1mifuht.sh
==> icinga2: Running provisioner: shell...
    icinga2: Running: inline script
==> icinga2: /sbin/ifup: configuration for eth1 not found.
==> icinga2: Usage: ifup <configuration>
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
</code>
</pre>
</details>

**Comment by dnsmichi** [comment]
That's coming from a workaround for Vagrant 1.8.5 - 1.9.1 which does not bring up the hostonly interface properly. Some users report to have a different naming schema for that interface, mine creates `eth1`.

```
      # workaround for Vagrant >1.8.4-1.9.1 not bringing up eth1 properly
      # https://github.com/mitchellh/vagrant/issues/8096
      app_config.vm.provision "shell", inline: "ifup eth1", run: "always"
```

You can modify such, or propose a better workaround. I don't have an idea how to properly fix that until Vagrant 1.9.2 is released which fixes that regression.

**Comment by lazyfrosch** [comment]
Linking the issue: https://github.com/mitchellh/vagrant/issues/8096

**Comment by dnsmichi** [comment]
I'll change the workaround to a generic tested fix, but still you should either downgrade to 1.8.4 or wait for 1.9.2 finally released. Or you'll manually apply the patch from mitchellh/vagrant#8096.

**Comment by dnsmichi** [comment]
https://github.com/mitchellh/vagrant/blob/v1.9.2/CHANGELOG.md
