### ISSUE TITLE
missing yum packages for graphite

### ISSUE THREAD

**Issue by cloos** [Icinga/icinga-vagrant#32]
To have a working graphite in the icinga2x vagrant box, I had to manually install the cairo-devel and libffi-devel yum packages (see http://graphite.readthedocs.io/en/latest/install-pip.html).

So please install these packages by default.

**Comment by dnsmichi** [comment]
What do you mean by "have a working graphite"? The Puppet provisioner pins the version to 0.9.14 - I would think that newer versions require those mentioned packages.

Can you elaborate more in detail what your problem is?

**Comment by cloos** [comment]
```
git clone https://github.com/Icinga/icinga-vagrant.git
cd icinga-vagrant/icinga2x
vagrant up
```
open http://192.168.33.5:8003
select any metric
graphite **can't** generate an image

```
vagrant ssh
sudo yum install cairo-devel libffi-devel
```
open http://192.168.33.5:8003
select any metric
graphite **can** generate an image

**Comment by dnsmichi** [comment]
Hm, that's really strange is it works for me with a newly provisioned box. Thanks though for noticing, I believe that the change with python2-pip broke some dependencies, or similar. 

![screen shot 2017-01-27 at 10 20 25](https://cloud.githubusercontent.com/assets/382049/22365901/47efe564-e47a-11e6-8e67-7bbc289b0434.png)

I'll keep this open for updating the puppet-graphite module as well, requiring the patches too.
