### ISSUE TITLE
/etc/vimrc has Windows line endings "^M"

### ISSUE THREAD

**Issue by Dumbaz** [Icinga/icinga-vagrant#50]
I am currently using the icinga2x/ box and ran into this small problem.

```
[root@icinga2 ~]# vim /etc/yum.conf
Error detected while processing /etc/vimrc:
line    3:
E492: Not an editor command: ^M
line    4:
E492: Not an editor command: ^M
line    5:
E488: Trailing characters: nocompatible^M
line    6:
E492: Not an editor command: ^M
line    7:
E492: Not an editor command: ^M
line    8:
E492: Not an editor command: ^M
line    9:
E492: Not an editor command: ^M
line   10:
E15: Invalid expression: has("syntax")^M
line   58:
E171: Missing :endif
Press ENTER or type command to continue
```

Deleting the line endings fixed the problem

I am on the current master branch

```
.../icinga-vagrant (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

The file does not seem to be configured during the puppet run or stem from the `\icinga2x\files` folder, so it it probably has to be changed in the `http://boxes.icinga.com/centos-71-x64-vbox.box` itself.

Windows 8.1 Host, VirtualBox Provider

**Comment by dnsmichi** [comment]
puppet-vim is managing the vimrc file, and as such uses the template file from your local Windows host. Since you've cloned that on Windows, I bet you forgot to set the crlf settings mentioned in the README file.

Can you please share the first two lines of /etc/vimrc in your Vagrant box?

**Comment by Dumbaz** [comment]
You´re probably right. Had no time to look into it yet, but here are the first 2 lines

```
" vimrc: Managed by puppet - DO NOT EDIT
" Changes manually to this file can, and will, be lost


set nocompatible
```

**Comment by Dumbaz** [comment]
As outlined in the Readme, I did not have this problem when I set the git option for line endings.

`git.exe config --global core.autocrlf false` before cloning the repository.

**Comment by dnsmichi** [comment]
Thanks for the feedback. I have tested that on Windows and have some changes pending for the docs to make it more clear. Also how to have that set during the Git installer dialog.
