### ISSUE TITLE
Update Graphite to 1.x

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-vagrant#63]
According to @mwaldmueller there's a bug with pip install and correct Python libraries. Holding off until there's time to analyze it. 

Might be related: https://answers.launchpad.net/graphite/+question/617303

**Comment by mwaldmueller** [comment]
The bug affects "carbon" and "graphite-web", "whisper" is working as expected. The following solution/workaround works for me:

```
# ln -s /opt/graphite/lib/carbon-1.0.0-py2.7.egg-info/ /usr/lib/python2.7/site-packages/
# ln -s /opt/graphite/webapp/graphite_web-1.0.0-py2.7.egg-info/ /usr/lib/python2.7/site-packages/
```

**Comment by dnsmichi** [comment]
That one is horrible. You need to 

- pin specific Python library version
- run a custom syncdb script override (for gods sake the latest puppet-graphite module supports that)
- override the provider from posix to shell
- collect static content within the syncdb operation, and also add an apache entry for just that
- fix the graphite web logs

Basically workaround everything, the final profile is not so good looking.

**Comment by dnsmichi** [comment]
![screen shot 2018-02-08 at 18 23 10](https://user-images.githubusercontent.com/382049/35987860-2b2936d6-0cfd-11e8-8d25-a25cdaa679c9.png)

**Comment by dnsmichi** [comment]
Implemented in feature/puppet-4 branch, merged soon.
