### ISSUE TITLE
Unable to mount Shared folder

### ISSUE THREAD

**Issue by fscaptain** [Icinga/icinga-vagrant#67]
vagrant up comes with the follwoing error (Vgrant 1.9.3, Virtualbox 1.5.20 running on Ubuntu 16.04)

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: wrong fs type, bad option, bad superblock on vagrant,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

Error comes from incorrect path in symlink for /sbin/mount.vboxsf .
```
[root@icinga2 ~]# ls -lh /sbin/mount.vboxsf 
lrwxrwxrwx. 1 root root 49 26. Apr 19:07 /sbin/mount.vboxsf -> /opt/VBoxGuestAdditions-5.1.20/other/mount.vboxsf
```

I fixed this with 
`[root@icinga2 ~]# cd /opt/VBoxGuestAdditions-5.1.20/sudo ln -sf /opt/VBoxGuestAdditions-5.1.20/lib/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf`

After logout a simple 'vagrant reload' runs the full provisioning.

Trying that in the "icinga2x" box, but seems also present in the other boxes using virtualbox

**Comment by lazyfrosch** [comment]
This is most likely a bug in VBoxGuestAdditions, as I discussed with a colleague last week.

Previous versions don't have that issue, and creation of that file is not related to Vagrant or the plugin.

Only way to mitigate it would be a workaround in the vbguest plugin.

Also see:
* https://stackoverflow.com/questions/43492322/vagrant-was-unable-to-mount-virtualbox-shared-folders

**Comment by lazyfrosch** [comment]
Upstream bug: https://www.virtualbox.org/ticket/16670

**Comment by dnsmichi** [comment]
Which version of icinga-vagrant are you using? 1.3.1 and git master do use base boxes which have the guest additions already installed.

**Comment by fscaptain** [comment]
icinga-vagrant ist git master and base box is bento/centos-7.3

**Comment by dnsmichi** [comment]
Host system is a Linux distribution or Windows?

**Comment by dnsmichi** [comment]
Hm, ok, saw that it is running on Ubuntu. Somewhat strange. Do you happen to have the `vagrant-vbguest` plugin installed?

**Comment by lazyfrosch** [comment]
Auto update is enabled by default...

**Comment by fscaptain** [comment]
jepp, vagrant-vbguest plugin is installed, otherwise provisioning doesn't work anyway.

**Comment by dnsmichi** [comment]
It does, since the box has the guest additions already installed. That plugin is starting to annoy me...

I'll see if I can come up with a possible solution for disabling this plugin's functionality.
