### ISSUE TITLE
icinga2x: php-mbstring missing

### ISSUE THREAD

**Issue by nbuchwitz** [Icinga/icinga-vagrant#85]
Missing php-mbstring module in manifest.pp

To reproduce the error go to ``Documentation`` -> ``Module documentations`` -> ``Icinga2`` -> ``Getting Started``

```
Fatal error: Call to undefined function mb_strlen() in /usr/share/icingaweb2/library/vendor/Parsedown/Parsedown.php on line 144
```
To fix this add the following line to ``manifests/default.pp``:

```
php::module { [ 'mbstring' ]: }
```

**Comment by dnsmichi** [comment]
Thanks 👍
