### ISSUE TITLE
Pin Icinga2 Server RPM to specific version?

### ISSUE THREAD

**Issue by ifischer** [Icinga/icinga-vagrant#95]
Is it possible to pin Icinga2-server version in Vagrant box to a specific release version rather than just choosing between "release" and "snapshot"?

We are currently running r2.6.3-1 in production and would like to compare against current stable/snapshot releases before upgrading.

**Comment by dnsmichi** [comment]
That's not supported by the underlaying Puppet module. You'll need to find your own method of pinning such packages.

**Comment by ifischer** [comment]
Ok thanks. Since we are running on Debian anyways I build my own vagrantfile for Debian which allows to specify the version easily. It's stripped down to be as minimalistic as possible. https://github.com/ifischer/icinga2-vagrant-minimal

**Comment by dnsmichi** [comment]
Hm yeah, then it isn't helpful when it runs on CentOS but breaks on Ubuntu. The boxes could work as an inspiration, but not for everyone as special test case. The major idea is to let users see the latest and greatest while they can also report bugs existing in unreleased versions.
