### ISSUE TITLE
icinga2x vagrant up does not provision, maybe due to nagvis not downloading?

### ISSUE THREAD

**Issue by jerrac** [Icinga/icinga-vagrant#96]
## Expected Behavior
Vagrant provisioning should complete successfully.

## Current Behavior
Vagrant provisioning does not complete successfully. 
See: https://gist.github.com/jerrac/597c9bc4eee3a1af37fdb279729ee434

Specifically, it appears that nagvis does not download correctly. I think.

If I go into the icinga2x-cluster directory and run vagrant up, it provisions successfully. Just FYI.

```
==> icinga2: Error: wget --no-verbose --output-document="/tmp/nagvis-1.9.2.tar.gz" "http://www.nagvis.org/share/nagvis-1.9.2.tar.gz" returned 4 instead of one of [0]
==> icinga2: Notice: /Stage[main]/Nagvis::Install/Exec[extract-nagvis]: Dependency Exec[wget-nagvis] has failures: true
==> icinga2: Error: /Stage[main]/Nagvis::Install/Wget::Fetch[nagvis]/Exec[wget-nagvis]/returns: change from notrun to 0 failed: wget --no-verbose --output-document="/tmp/nagvis-1.9.2.tar.gz" "http://www.nagvis.org/share/nagvis-1.9.2.tar.gz" returned 4 instead of one of [0]
==> icinga2: Warning: /Stage[main]/Nagvis::Install/Exec[extract-nagvis]: Skipping because of failed dependencies
```

## Steps to Reproduce (for bugs)

1. Install vagrant for the first time.
2. Install virtualbox for the first time.
3. Check out this repo.
4. cd /path/to/repo/icinga2x ; vagrant up

## Context
I'm trying to test icinga. Nothing complicated.

## Your Environment

* Vagrant version (`vagrant -v`): Vagrant 2.0.0
* Box name: icinga2x
* Release version: ? I checked out the master branch of this repo.
* Operating system: CentOS 7
* Provider (VirtualBox, Parallels, libvirt): Virtualbox 5.1.26

**Comment by nbuchwitz** [comment]
Have you tried if you could download the nagvis archive (http://www.nagvis.org/share/nagvis-1.9.2.tar.gz) in your browser? I looked in your log file and didn't noticed any icinga or vagrant related error.

If the download is successful try a ```vagrant reload --provision```

**Comment by dnsmichi** [comment]
Could be a network issue for nagvis.org - did you try to run `vagrant provision` again?

**Comment by dnsmichi** [comment]
Did a fresh run today, works for me.
